export const FASES_PADRAO = [
  { numero:1,  nome:"Adequações de terreno: terraplenagem e arrimos", is_variavel:true,  proporcao:null,  descricao:"Preparação e nivelamento do terreno, arrimos e contenções." },
  { numero:2,  nome:"Canteiro e despesas gerais",                     is_variavel:false, proporcao:1.5,   descricao:"Instalação do canteiro de obras e despesas administrativas gerais." },
  { numero:3,  nome:"Serviços preliminares",                          is_variavel:false, proporcao:1.0,   descricao:"Locação da obra, demolições, limpeza inicial." },
  { numero:4,  nome:"Fundação",                                       is_variavel:false, proporcao:6.0,   descricao:"Escavações, estacas, sapatas e blocos de fundação." },
  { numero:5,  nome:"Estrutura",                                      is_variavel:false, proporcao:16.0,  descricao:"Pilares, vigas e lajes de concreto armado." },
  { numero:6,  nome:"Alvenaria",                                      is_variavel:false, proporcao:3.0,   descricao:"Execução das paredes em alvenaria de tijolo ou bloco." },
  { numero:7,  nome:"Revestimentos argamassados",                     is_variavel:false, proporcao:3.0,   descricao:"Reboco interno e externo, chapisco e emboço." },
  { numero:8,  nome:"Instalações elétricas",                          is_variavel:false, proporcao:2.5,   descricao:"Eletrodutos, fiação, quadros elétricos e pontos de luz/tomada." },
  { numero:9,  nome:"Instalações hidráulicas",                        is_variavel:false, proporcao:1.5,   descricao:"Tubulações de água fria, quente, esgoto e pluvial." },
  { numero:10, nome:"Instalações especiais",                          is_variavel:false, proporcao:1.0,   descricao:"SPDA, gás, automação, aquecimento, fotovoltaica, pressurização." },
  { numero:11, nome:"Impermeabilizações",                             is_variavel:false, proporcao:3.0,   descricao:"Impermeabilização de lajes, banheiros, piscinas e áreas molhadas." },
  { numero:12, nome:"Acabamentos",                                    is_variavel:false, proporcao:18.0,  descricao:"Revestimentos de piso, parede, rodapés e acabamentos em geral." },
  { numero:13, nome:"Cobertura",                                      is_variavel:false, proporcao:3.0,   descricao:"Estrutura de madeira/metálica, telhas e calhas." },
  { numero:14, nome:"Esquadrias e vidros",                            is_variavel:false, proporcao:15.0,  descricao:"Portas, janelas de alumínio/madeira, vidros temperados e box." },
  { numero:15, nome:"Luminotécnica",                                  is_variavel:false, proporcao:6.0,   descricao:"Projeto e instalação de luminárias, spots e iluminação decorativa." },
  { numero:16, nome:"Marmoraria, Louças e Metais",                    is_variavel:false, proporcao:6.0,   descricao:"Bancadas em pedra natural, louças sanitárias e metais." },
  { numero:17, nome:"Forros",                                         is_variavel:false, proporcao:3.0,   descricao:"Forros de gesso, madeira, vinílico ou PVC." },
  { numero:18, nome:"Pintura interna e externa",                      is_variavel:false, proporcao:3.0,   descricao:"Pintura lisa, texturizada, cimento queimado e vernizes." },
  { numero:19, nome:"Pavimentações e área verde",                     is_variavel:false, proporcao:1.0,   descricao:"Calçadas, pisos externos, jardins e paisagismo." },
  { numero:20, nome:"Finalização",                                    is_variavel:false, proporcao:1.0,   descricao:"Limpeza final, ajustes, vistoria e entrega." },
  { numero:21, nome:"Contratos especiais",                            is_variavel:false, proporcao:4.0,   descricao:"Piscina, sauna, home cinema, elevador e outros contratos especiais." },
  { numero:22, nome:"Locação de equipamentos",                        is_variavel:false, proporcao:1.5,   descricao:"Andaimes, gruas, caçambas e equipamentos locados." },
  { numero:23, nome:"Marcenaria",                                     is_variavel:true,  proporcao:null,  descricao:"Armários planejados, painéis, estantes e marcenaria em geral." },
]

export const MOMENTOS_PADRAO = [
  {
    numero: 0,
    nome: "Pré-Obra",
    descricao: "Regularizações, projetos e aprovações antes do início da obra.",
    prazo_estimado_min: null,
    prazo_estimado_max: null,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Regularização do terreno", tipo: "atividade", descricao: "Ajustes legais e físicos do terreno", fase_numeros: [1] },
      { nome: "Alvará de construção", tipo: "aquisicao_critica", descricao: "Aprovação junto à prefeitura" },
      { nome: "ART — Anotação de Responsabilidade Técnica", tipo: "aquisicao_critica", descricao: "Registro no CREA/CAU" },
      { nome: "Matrícula / CNO com contador / INSS (RFB)", tipo: "aquisicao_critica", descricao: "Cadastro Nacional de Obras" },
      { nome: "Elaborar planilha de custos", tipo: "atividade", descricao: "Orçamento detalhado da obra" },
      { nome: "Cronograma Físico × Financeiro", tipo: "atividade", descricao: "Planejamento de execução vs. desembolso" },
      { nome: "Aprovação de crédito (se necessário)", tipo: "atividade", descricao: "Financiamento ou crédito bancário" },
      { nome: "Projetos compatibilizados", tipo: "atividade", descricao: "Arquitetônico, estrutural, hidráulico e elétrico compatibilizados" },
    ]
  },
  {
    numero: 1,
    nome: "Momento 1 — Fundação",
    descricao: "Ajustes finais de terreno e execução da fundação.",
    prazo_estimado_min: 0.5,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Ajustes finais de terreno", tipo: "atividade", fase_numeros: [1] },
      { nome: "Execução da fundação", tipo: "atividade", descricao: "Estaca: ~2 semanas | Sapata: até 2 meses", fase_numeros: [4] },
      { nome: "Testar hipóteses estruturais", tipo: "atividade", descricao: "Validar com estrutural antes de avançar" },
      { nome: "Assinar contrato — Mão de obra fase grossa (5%)", tipo: "contrato" },
      { nome: "Assinar contrato — Eletricista (10%)", tipo: "contrato" },
      { nome: "Assinar contrato — Encanador / Bombeiro hidráulico (4%)", tipo: "contrato" },
      { nome: "Aquisição crítica: Esquadrias — iniciar processo de compra", tipo: "aquisicao_critica", fase_numeros: [14] },
      { nome: "Aquisição crítica: Piscina — contratar / definir projeto", tipo: "aquisicao_critica", fase_numeros: [21] },
      { nome: "Aquisição crítica: Automação — definir sistema", tipo: "aquisicao_critica", fase_numeros: [10] },
    ]
  },
  {
    numero: 2,
    nome: "Momento 2 — Alvenaria e Estrutura",
    descricao: "Execução das paredes e estrutura de concreto.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Alvenaria (tijolo)", tipo: "atividade", fase_numeros: [6] },
      { nome: "Estrutura — pilares, vigas e lajes", tipo: "atividade", fase_numeros: [5] },
      { nome: "Aquisição crítica: Compra dos revestimentos", tipo: "aquisicao_critica", fase_numeros: [12] },
      { nome: "Aquisição crítica: Sistema de fachada", tipo: "aquisicao_critica" },
      { nome: "Aquisição crítica: Louças e metais", tipo: "aquisicao_critica", fase_numeros: [16] },
      { nome: "Visita ao fornecedor de esquadrias (1ª visita)", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 3,
    nome: "Momento 3 — Reboco e Instalações",
    descricao: "Reboco externo, instalações internas e contramarcos.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Reboco externo", tipo: "atividade", fase_numeros: [7] },
      { nome: "Operação anti-retrabalho — instalações internas", tipo: "atividade", descricao: "Toda passagem de tubulação elétrica e hidráulica antes de rebocar internamente", fase_numeros: [8, 9] },
      { nome: "Contramarcos de esquadria", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 4,
    nome: "Momento 4 — Cobertura e Reboco Interno",
    descricao: "Execução da cobertura e reboco interno.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Cobertura", tipo: "atividade", fase_numeros: [13] },
      { nome: "Reboco interno (massa ou gesso)", tipo: "atividade", fase_numeros: [7] },
      { nome: "Contramarcos finais", tipo: "atividade", fase_numeros: [14] },
      { nome: "Aquisição crítica: Marmoraria / bancadas", tipo: "aquisicao_critica", fase_numeros: [16] },
      { nome: "Aquisição crítica: Luminotécnica", tipo: "aquisicao_critica", fase_numeros: [15] },
      { nome: "Aquisição crítica: Eletrodomésticos", tipo: "aquisicao_critica" },
      { nome: "Aquisição crítica: Marcenaria", tipo: "aquisicao_critica", fase_numeros: [23] },
    ]
  },
  {
    numero: 5,
    nome: "Momento 5 — Pintura Externa, Impermeabilizações e Forros",
    descricao: "Acabamento externo, impermeabilizações e forros internos.",
    prazo_estimado_min: 1.5,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Pintura externa (lisa, textura ou cimento queimado)", tipo: "atividade", fase_numeros: [18] },
      { nome: "Forros (gesso, madeira, vinílico ou PVC)", tipo: "atividade", fase_numeros: [17] },
      { nome: "Revestimento de paredes", tipo: "atividade", fase_numeros: [12] },
      { nome: "Impermeabilizações (piscina, varandas, sacadas, banheiros)", tipo: "atividade", fase_numeros: [11] },
      { nome: "Visita ao fornecedor de esquadrias (confirmação entrega)", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 6,
    nome: "Momento 6 — Revestimentos, Bancadas e Sistemas",
    descricao: "Piso, bancadas, piscina e sistemas especiais.",
    prazo_estimado_min: 2,
    prazo_estimado_max: 2.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Revestimento de piso", tipo: "atividade", fase_numeros: [12] },
      { nome: "Bancadas (marmoraria)", tipo: "atividade", fase_numeros: [16] },
      { nome: "Revestimento de piscina", tipo: "atividade", fase_numeros: [21] },
      { nome: "Sistemas: piscina, aquecimento, fotovoltaica, pressurização", tipo: "atividade", fase_numeros: [10] },
      { nome: "Instalação de luminárias", tipo: "atividade", fase_numeros: [15] },
    ]
  },
  {
    numero: 7,
    nome: "Momento 7 — Pintura Interna, Calçada e Paisagismo",
    descricao: "Acabamentos internos e externos finais.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Pintura interna", tipo: "atividade", fase_numeros: [18] },
      { nome: "Calçada", tipo: "atividade", fase_numeros: [19] },
      { nome: "Grama / Paisagismo", tipo: "atividade", fase_numeros: [19] },
      { nome: "Instalação de luminárias (finalização)", tipo: "atividade", fase_numeros: [15] },
    ]
  },
  {
    numero: 8,
    nome: "Momento 8 — Acabamentos Finais e Entrega",
    descricao: "Instalação de esquadrias, finalização elétrica e limpeza final.",
    prazo_estimado_min: 0.5,
    prazo_estimado_max: 1,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Instalação de esquadrias (contato constante com fornecedor)", tipo: "atividade", fase_numeros: [14] },
      { nome: "Portas prontas", tipo: "atividade", fase_numeros: [14] },
      { nome: "Finalização elétrica", tipo: "atividade", fase_numeros: [8] },
      { nome: "Limpeza final", tipo: "atividade", fase_numeros: [20] },
    ]
  },
]

export const INSUMOS_PADRAO = [
  { ranking:1,  classe:"A", nome:"Esquadrias de alumínio",       categoria:"Esquadrias",      peso_percentual:12.4 },
  { ranking:2,  classe:"A", nome:"Revestimento: pedra natural",  categoria:"Revestimentos",   peso_percentual:11.7 },
  { ranking:3,  classe:"A", nome:"Marcenaria",                   categoria:"Marcenaria",      peso_percentual:10.8 },
  { ranking:4,  classe:"A", nome:"Vigas metálicas",              categoria:"Estrutura",       peso_percentual:5.5  },
  { ranking:5,  classe:"A", nome:"Marmoraria",                   categoria:"Acabamentos",     peso_percentual:5.5  },
  { ranking:6,  classe:"A", nome:"Concreto",                     categoria:"Estrutura",       peso_percentual:5.2  },
  { ranking:7,  classe:"A", nome:"Aço",                          categoria:"Estrutura",       peso_percentual:3.9  },
  { ranking:8,  classe:"A", nome:"Louças e metais",              categoria:"Hidráulica",      peso_percentual:2.8  },
  { ranking:9,  classe:"A", nome:"Madeira para fôrma",           categoria:"Estrutura",       peso_percentual:2.5  },
  { ranking:10, classe:"A", nome:"Forro de madeira",             categoria:"Forros",          peso_percentual:2.4  },
  { ranking:11, classe:"B", nome:"Luminárias e spots",           categoria:"Elétrica",        peso_percentual:2.2  },
  { ranking:12, classe:"B", nome:"Revestimento cerâmico",        categoria:"Revestimentos",   peso_percentual:2.0  },
  { ranking:13, classe:"B", nome:"Impermeabilizante",            categoria:"Impermeabilização",peso_percentual:1.9 },
  { ranking:14, classe:"B", nome:"Tintas",                       categoria:"Pintura",         peso_percentual:1.8  },
  { ranking:15, classe:"B", nome:"Gesso em placa",               categoria:"Forros",          peso_percentual:1.6  },
  { ranking:16, classe:"B", nome:"Instalação elétrica (fio)",    categoria:"Elétrica",        peso_percentual:1.5  },
  { ranking:17, classe:"B", nome:"Tubulação hidráulica",         categoria:"Hidráulica",      peso_percentual:1.4  },
  { ranking:18, classe:"B", nome:"Bloco cerâmico",               categoria:"Alvenaria",       peso_percentual:1.3  },
  { ranking:19, classe:"B", nome:"Cimento",                      categoria:"Estrutura",       peso_percentual:1.2  },
  { ranking:20, classe:"B", nome:"Areia",                        categoria:"Estrutura",       peso_percentual:1.1  },
  { ranking:21, classe:"B", nome:"Brita",                        categoria:"Estrutura",       peso_percentual:1.0  },
  { ranking:22, classe:"B", nome:"Porcelanato",                  categoria:"Revestimentos",   peso_percentual:0.9  },
  { ranking:23, classe:"B", nome:"Cal",                          categoria:"Revestimentos",   peso_percentual:0.8  },
  { ranking:24, classe:"B", nome:"Vidros temperados",            categoria:"Esquadrias",      peso_percentual:0.8  },
  { ranking:25, classe:"B", nome:"Telha",                        categoria:"Cobertura",       peso_percentual:0.7  },
  { ranking:26, classe:"C", nome:"Estrutura de madeira (telhado)",categoria:"Cobertura",      peso_percentual:0.6  },
  { ranking:27, classe:"C", nome:"Calha e rufo",                 categoria:"Cobertura",       peso_percentual:0.5  },
  { ranking:28, classe:"C", nome:"Massa corrida PVA",            categoria:"Pintura",         peso_percentual:0.5  },
  { ranking:29, classe:"C", nome:"Rodapé",                       categoria:"Acabamentos",     peso_percentual:0.5  },
  { ranking:30, classe:"C", nome:"Rejunte",                      categoria:"Revestimentos",   peso_percentual:0.4  },
  { ranking:31, classe:"C", nome:"Argamassa colante",            categoria:"Revestimentos",   peso_percentual:0.4  },
  { ranking:32, classe:"C", nome:"Parafuso e bucha",             categoria:"Ferragens",       peso_percentual:0.3  },
  { ranking:33, classe:"C", nome:"Grelha e ralo",                categoria:"Hidráulica",      peso_percentual:0.3  },
  { ranking:34, classe:"C", nome:"Tomada e interruptor",         categoria:"Elétrica",        peso_percentual:0.3  },
  { ranking:35, classe:"C", nome:"Disjuntores",                  categoria:"Elétrica",        peso_percentual:0.3  },
]
