export const FASES_PADRAO = [
  { numero:1,  nome:"Adequações de terreno: terraplenagem e arrimos", is_variavel:true,  proporcao:null,  descricao:"Preparação e nivelamento do terreno, arrimos e contenções." },
  { numero:2,  nome:"Canteiro e despesas gerais",                     is_variavel:false, proporcao:1.5,   descricao:"Instalação do canteiro de obras e despesas administrativas gerais." },
  { numero:3,  nome:"Serviços preliminares",                          is_variavel:false, proporcao:1.0,   descricao:"Locação da obra, demolições, limpeza inicial." },
  { numero:4,  nome:"Fundação",                                       is_variavel:false, proporcao:6.0,   descricao:"Escavações, estacas, sapatas e blocos de fundação." },
  { numero:5,  nome:"Estrutura",                                      is_variavel:false, proporcao:16.0,  descricao:"Pilares, vigas e lajes de concreto armado." },
  { numero:6,  nome:"Alvenaria",                                      is_variavel:false, proporcao:3.0,   descricao:"Execução das paredes em alvenaria de tijolo ou bloco." },
  { numero:7,  nome:"Revestimentos argamassados",                     is_variavel:false, proporcao:3.0,   descricao:"Reboco interno e externo, chapisco e emboço." },
  { numero:8,  nome:"Instalações elétricas",                          is_variavel:false, proporcao:2.5,   descricao:"Eletrodutos, fiação, quadros elétricos e pontos de luz/tomada." },
  { numero:9,  nome:"Instalações hidráulicas",                        is_variavel:false, proporcao:1.5,   descricao:"Tubulações de água fria, quente, esgoto e pluvial." },
  { numero:10, nome:"Instalações especiais",                          is_variavel:false, proporcao:1.0,   descricao:"SPDA, gás, automação, aquecimento, fotovoltaica, pressurização." },
  { numero:11, nome:"Impermeabilizações",                             is_variavel:false, proporcao:3.0,   descricao:"Impermeabilização de lajes, banheiros, piscinas e áreas molhadas." },
  { numero:12, nome:"Acabamentos",                                    is_variavel:false, proporcao:18.0,  descricao:"Revestimentos de piso, parede, rodapés e acabamentos em geral." },
  { numero:13, nome:"Cobertura",                                      is_variavel:false, proporcao:3.0,   descricao:"Estrutura de madeira/metálica, telhas e calhas." },
  { numero:14, nome:"Esquadrias e vidros",                            is_variavel:false, proporcao:15.0,  descricao:"Portas, janelas de alumínio/madeira, vidros temperados e box." },
  { numero:15, nome:"Luminotécnica",                                  is_variavel:false, proporcao:6.0,   descricao:"Projeto e instalação de luminárias, spots e iluminação decorativa." },
  { numero:16, nome:"Marmoraria, Louças e Metais",                    is_variavel:false, proporcao:6.0,   descricao:"Bancadas em pedra natural, louças sanitárias e metais." },
  { numero:17, nome:"Forros",                                         is_variavel:false, proporcao:3.0,   descricao:"Forros de gesso, madeira, vinílico ou PVC." },
  { numero:18, nome:"Pintura interna e externa",                      is_variavel:false, proporcao:3.0,   descricao:"Pintura lisa, texturizada, cimento queimado e vernizes." },
  { numero:19, nome:"Pavimentações e área verde",                     is_variavel:false, proporcao:1.0,   descricao:"Calçadas, pisos externos, jardins e paisagismo." },
  { numero:20, nome:"Finalização",                                    is_variavel:false, proporcao:1.0,   descricao:"Limpeza final, ajustes, vistoria e entrega." },
  { numero:21, nome:"Contratos especiais",                            is_variavel:false, proporcao:4.0,   descricao:"Piscina, sauna, home cinema, elevador e outros contratos especiais." },
  { numero:22, nome:"Locação de equipamentos",                        is_variavel:false, proporcao:1.5,   descricao:"Andaimes, gruas, caçambas e equipamentos locados." },
  { numero:23, nome:"Marcenaria",                                     is_variavel:true,  proporcao:null,  descricao:"Armários planejados, painéis, estantes e marcenaria em geral." },
]

export const MOMENTOS_PADRAO = [
  {
    numero: 0,
    nome: "Pré-Obra",
    descricao: "Regularizações, projetos e aprovações antes do início da obra.",
    prazo_estimado_min: null,
    prazo_estimado_max: null,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Regularização do terreno", tipo: "atividade", descricao: "Ajustes legais e físicos do terreno", fase_numeros: [1] },
      { nome: "Alvará de construção", tipo: "aquisicao_critica", descricao: "Aprovação junto à prefeitura" },
      { nome: "ART — Anotação de Responsabilidade Técnica", tipo: "aquisicao_critica", descricao: "Registro no CREA/CAU" },
      { nome: "Matrícula / CNO com contador / INSS (RFB)", tipo: "aquisicao_critica", descricao: "Cadastro Nacional de Obras" },
      { nome: "Elaborar planilha de custos", tipo: "atividade", descricao: "Orçamento detalhado da obra" },
      { nome: "Cronograma Físico × Financeiro", tipo: "atividade", descricao: "Planejamento de execução vs. desembolso" },
      { nome: "Aprovação de crédito (se necessário)", tipo: "atividade", descricao: "Financiamento ou crédito bancário" },
      { nome: "Projetos compatibilizados", tipo: "atividade", descricao: "Arquitetônico, estrutural, hidráulico e elétrico compatibilizados" },
    ]
  },
  {
    numero: 1,
    nome: "Momento 1 — Fundação",
    descricao: "Ajustes finais de terreno e execução da fundação.",
    prazo_estimado_min: 0.5,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Ajustes finais de terreno", tipo: "atividade", fase_numeros: [1] },
      { nome: "Execução da fundação", tipo: "atividade", descricao: "Estaca: ~2 semanas | Sapata: até 2 meses", fase_numeros: [4] },
      { nome: "Testar hipóteses estruturais", tipo: "atividade", descricao: "Validar com estrutural antes de avançar" },
      { nome: "Assinar contrato — Mão de obra fase grossa (5%)", tipo: "contrato" },
      { nome: "Assinar contrato — Eletricista (10%)", tipo: "contrato" },
      { nome: "Assinar contrato — Encanador / Bombeiro hidráulico (4%)", tipo: "contrato" },
      { nome: "Aquisição crítica: Esquadrias — iniciar processo de compra", tipo: "aquisicao_critica", fase_numeros: [14] },
      { nome: "Aquisição crítica: Piscina — contratar / definir projeto", tipo: "aquisicao_critica", fase_numeros: [21] },
      { nome: "Aquisição crítica: Automação — definir sistema", tipo: "aquisicao_critica", fase_numeros: [10] },
    ]
  },
  {
    numero: 2,
    nome: "Momento 2 — Alvenaria e Estrutura",
    descricao: "Execução das paredes e estrutura de concreto.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Alvenaria (tijolo)", tipo: "atividade", fase_numeros: [6] },
      { nome: "Estrutura — pilares, vigas e lajes", tipo: "atividade", fase_numeros: [5] },
      { nome: "Aquisição crítica: Compra dos revestimentos", tipo: "aquisicao_critica", fase_numeros: [12] },
      { nome: "Aquisição crítica: Sistema de fachada", tipo: "aquisicao_critica" },
      { nome: "Aquisição crítica: Louças e metais", tipo: "aquisicao_critica", fase_numeros: [16] },
      { nome: "Visita ao fornecedor de esquadrias (1ª visita)", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 3,
    nome: "Momento 3 — Reboco e Instalações",
    descricao: "Reboco externo, instalações internas e contramarcos.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Reboco externo", tipo: "atividade", fase_numeros: [7] },
      { nome: "Operação anti-retrabalho — instalações internas", tipo: "atividade", descricao: "Toda passagem de tubulação elétrica e hidráulica antes de rebocar internamente", fase_numeros: [8, 9] },
      { nome: "Contramarcos de esquadria", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 4,
    nome: "Momento 4 — Cobertura e Reboco Interno",
    descricao: "Execução da cobertura e reboco interno.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Cobertura", tipo: "atividade", fase_numeros: [13] },
      { nome: "Reboco interno (massa ou gesso)", tipo: "atividade", fase_numeros: [7] },
      { nome: "Contramarcos finais", tipo: "atividade", fase_numeros: [14] },
      { nome: "Aquisição crítica: Marmoraria / bancadas", tipo: "aquisicao_critica", fase_numeros: [16] },
      { nome: "Aquisição crítica: Luminotécnica", tipo: "aquisicao_critica", fase_numeros: [15] },
      { nome: "Aquisição crítica: Eletrodomésticos", tipo: "aquisicao_critica" },
      { nome: "Aquisição crítica: Marcenaria", tipo: "aquisicao_critica", fase_numeros: [23] },
    ]
  },
  {
    numero: 5,
    nome: "Momento 5 — Pintura Externa, Impermeabilizações e Forros",
    descricao: "Acabamento externo, impermeabilizações e forros internos.",
    prazo_estimado_min: 1.5,
    prazo_estimado_max: 2,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Pintura externa (lisa, textura ou cimento queimado)", tipo: "atividade", fase_numeros: [18] },
      { nome: "Forros (gesso, madeira, vinílico ou PVC)", tipo: "atividade", fase_numeros: [17] },
      { nome: "Revestimento de paredes", tipo: "atividade", fase_numeros: [12] },
      { nome: "Impermeabilizações (piscina, varandas, sacadas, banheiros)", tipo: "atividade", fase_numeros: [11] },
      { nome: "Visita ao fornecedor de esquadrias (confirmação entrega)", tipo: "atividade", fase_numeros: [14] },
    ]
  },
  {
    numero: 6,
    nome: "Momento 6 — Revestimentos, Bancadas e Sistemas",
    descricao: "Piso, bancadas, piscina e sistemas especiais.",
    prazo_estimado_min: 2,
    prazo_estimado_max: 2.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Revestimento de piso", tipo: "atividade", fase_numeros: [12] },
      { nome: "Bancadas (marmoraria)", tipo: "atividade", fase_numeros: [16] },
      { nome: "Revestimento de piscina", tipo: "atividade", fase_numeros: [21] },
      { nome: "Sistemas: piscina, aquecimento, fotovoltaica, pressurização", tipo: "atividade", fase_numeros: [10] },
      { nome: "Instalação de luminárias", tipo: "atividade", fase_numeros: [15] },
    ]
  },
  {
    numero: 7,
    nome: "Momento 7 — Pintura Interna, Calçada e Paisagismo",
    descricao: "Acabamentos internos e externos finais.",
    prazo_estimado_min: 1,
    prazo_estimado_max: 1.5,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Pintura interna", tipo: "atividade", fase_numeros: [18] },
      { nome: "Calçada", tipo: "atividade", fase_numeros: [19] },
      { nome: "Grama / Paisagismo", tipo: "atividade", fase_numeros: [19] },
      { nome: "Instalação de luminárias (finalização)", tipo: "atividade", fase_numeros: [15] },
    ]
  },
  {
    numero: 8,
    nome: "Momento 8 — Acabamentos Finais e Entrega",
    descricao: "Instalação de esquadrias, finalização elétrica e limpeza final.",
    prazo_estimado_min: 0.5,
    prazo_estimado_max: 1,
    prerequisito_ids: [],
    tarefas: [
      { nome: "Instalação de esquadrias (contato constante com fornecedor)", tipo: "atividade", fase_numeros: [14] },
      { nome: "Portas prontas", tipo: "atividade", fase_numeros: [14] },
      { nome: "Finalização elétrica", tipo: "atividade", fase_numeros: [8] },
      { nome: "Limpeza final", tipo: "atividade", fase_numeros: [20] },
    ]
  },
]

// fase_numero refere-se ao numero da FASES_PADRAO (1-23)
// momento_numero refere-se ao numero do MOMENTOS_PADRAO (0-8)
export const INSUMOS_PADRAO = [
  { ranking:1,  classe:"A", nome:"Esquadrias de alumínio",              categoria:"Esquadrias",           peso_percentual:12.38, fase_numero:14, momento_numero:1  },
  { ranking:2,  classe:"A", nome:"Revestimento: pedra natural",         categoria:"Revestimentos",        peso_percentual:11.75, fase_numero:12, momento_numero:2  },
  { ranking:3,  classe:"A", nome:"Marcenaria",                          categoria:"Marcenaria",           peso_percentual:10.84, fase_numero:23, momento_numero:4  },
  { ranking:4,  classe:"A", nome:"Vigas metálicas",                     categoria:"Estrutura",            peso_percentual:5.48,  fase_numero:5,  momento_numero:2  },
  { ranking:5,  classe:"A", nome:"Marmoraria",                          categoria:"Acabamentos",          peso_percentual:5.50,  fase_numero:16, momento_numero:4  },
  { ranking:6,  classe:"A", nome:"Concreto",                            categoria:"Estrutura",            peso_percentual:5.17,  fase_numero:5,  momento_numero:2  },
  { ranking:7,  classe:"A", nome:"Aço",                                 categoria:"Estrutura",            peso_percentual:3.90,  fase_numero:5,  momento_numero:2  },
  { ranking:8,  classe:"A", nome:"Louças e metais",                     categoria:"Hidráulica",           peso_percentual:2.81,  fase_numero:16, momento_numero:2  },
  { ranking:9,  classe:"A", nome:"Madeira para fôrma (estrutura)",      categoria:"Estrutura",            peso_percentual:2.46,  fase_numero:5,  momento_numero:2  },
  { ranking:10, classe:"A", nome:"Forro de madeira",                    categoria:"Forros",               peso_percentual:2.44,  fase_numero:17, momento_numero:5  },
  { ranking:11, classe:"B", nome:"Contrato Automação",                  categoria:"Automação",            peso_percentual:2.10,  fase_numero:10, momento_numero:1  },
  { ranking:12, classe:"B", nome:"Equipamentos",                        categoria:"Equipamentos",         peso_percentual:2.30,  fase_numero:22, momento_numero:2  },
  { ranking:13, classe:"B", nome:"Aditivos e impermeabilizantes",       categoria:"Impermeabilização",    peso_percentual:1.87,  fase_numero:11, momento_numero:5  },
  { ranking:14, classe:"B", nome:"Escoramento",                         categoria:"Estrutura",            peso_percentual:1.78,  fase_numero:5,  momento_numero:2  },
  { ranking:15, classe:"B", nome:"Deck de madeira",                     categoria:"Acabamentos",          peso_percentual:1.54,  fase_numero:12, momento_numero:6  },
  { ranking:16, classe:"B", nome:"Materiais hidráulicos",               categoria:"Hidráulica",           peso_percentual:1.52,  fase_numero:9,  momento_numero:3  },
  { ranking:17, classe:"B", nome:"Luminotécnica",                       categoria:"Elétrica",             peso_percentual:1.48,  fase_numero:15, momento_numero:4  },
  { ranking:18, classe:"B", nome:"Paisagismo e grama",                  categoria:"Paisagismo",           peso_percentual:1.43,  fase_numero:19, momento_numero:7  },
  { ranking:19, classe:"B", nome:"Revestimento: madeira",               categoria:"Revestimentos",        peso_percentual:1.86,  fase_numero:12, momento_numero:6  },
  { ranking:20, classe:"B", nome:"Material elétrico",                   categoria:"Elétrica",             peso_percentual:1.25,  fase_numero:8,  momento_numero:3  },
  { ranking:21, classe:"B", nome:"Eletrodomésticos",                    categoria:"Equipamentos",         peso_percentual:1.13,  fase_numero:21, momento_numero:4  },
  { ranking:22, classe:"B", nome:"Outros",                              categoria:"Outros",               peso_percentual:0.99,  fase_numero:null, momento_numero:null },
  { ranking:23, classe:"B", nome:"Materiais de pintura",                categoria:"Pintura",              peso_percentual:0.98,  fase_numero:18, momento_numero:5  },
  { ranking:24, classe:"B", nome:"Energia fotovoltaica",                categoria:"Instalações Especiais",peso_percentual:0.97,  fase_numero:10, momento_numero:6  },
  { ranking:25, classe:"B", nome:"Condomínio",                          categoria:"Taxas",                peso_percentual:0.95,  fase_numero:2,  momento_numero:null },
  { ranking:26, classe:"C", nome:"Miudezas de depósito",                categoria:"Outros",               peso_percentual:0.95,  fase_numero:2,  momento_numero:2  },
  { ranking:27, classe:"C", nome:"Andaimes",                            categoria:"Locações",             peso_percentual:0.90,  fase_numero:22, momento_numero:2  },
  { ranking:28, classe:"C", nome:"Banheira",                            categoria:"Hidráulica",           peso_percentual:0.84,  fase_numero:16, momento_numero:2  },
  { ranking:29, classe:"C", nome:"Irrigação",                           categoria:"Paisagismo",           peso_percentual:0.73,  fase_numero:19, momento_numero:7  },
  { ranking:30, classe:"C", nome:"Forro de gesso",                      categoria:"Forros",               peso_percentual:0.71,  fase_numero:17, momento_numero:5  },
  { ranking:31, classe:"C", nome:"Fretes",                              categoria:"Logística",            peso_percentual:0.67,  fase_numero:2,  momento_numero:null },
  { ranking:32, classe:"C", nome:"Areia",                               categoria:"Estrutura",            peso_percentual:0.62,  fase_numero:5,  momento_numero:2  },
  { ranking:33, classe:"C", nome:"Argamassas",                          categoria:"Revestimentos",        peso_percentual:0.59,  fase_numero:7,  momento_numero:3  },
  { ranking:34, classe:"C", nome:"Adequações de terreno",               categoria:"Terreno",              peso_percentual:0.52,  fase_numero:1,  momento_numero:1  },
  { ranking:35, classe:"C", nome:"Cimento",                             categoria:"Estrutura",            peso_percentual:0.51,  fase_numero:5,  momento_numero:2  },
  { ranking:36, classe:"C", nome:"Rejuntamento",                        categoria:"Revestimentos",        peso_percentual:0.49,  fase_numero:12, momento_numero:6  },
  { ranking:37, classe:"C", nome:"Impostos",                            categoria:"Taxas",                peso_percentual:0.48,  fase_numero:2,  momento_numero:null },
  { ranking:38, classe:"C", nome:"Manta asfáltica",                     categoria:"Impermeabilização",    peso_percentual:0.42,  fase_numero:11, momento_numero:5  },
  { ranking:39, classe:"C", nome:"Caçambas",                            categoria:"Logística",            peso_percentual:0.36,  fase_numero:2,  momento_numero:1  },
  { ranking:40, classe:"C", nome:"Lajes e pré-moldados",                categoria:"Estrutura",            peso_percentual:0.35,  fase_numero:5,  momento_numero:2  },
  { ranking:41, classe:"C", nome:"Cartório",                            categoria:"Taxas",                peso_percentual:0.34,  fase_numero:3,  momento_numero:0  },
  { ranking:42, classe:"C", nome:"Blocos e tijolos cerâmicos",          categoria:"Alvenaria",            peso_percentual:0.34,  fase_numero:6,  momento_numero:2  },
  { ranking:43, classe:"C", nome:"Furação mecanizada (fundação)",       categoria:"Fundação",             peso_percentual:0.33,  fase_numero:4,  momento_numero:1  },
  { ranking:44, classe:"C", nome:"Tratamento de concreto",              categoria:"Estrutura",            peso_percentual:0.33,  fase_numero:5,  momento_numero:2  },
  { ranking:45, classe:"C", nome:"IPTU",                                categoria:"Taxas",                peso_percentual:0.31,  fase_numero:2,  momento_numero:null },
  { ranking:46, classe:"C", nome:"Aplicação de impermeabilização",      categoria:"Impermeabilização",    peso_percentual:0.28,  fase_numero:11, momento_numero:5  },
  { ranking:47, classe:"C", nome:"Arames e pregos",                     categoria:"Ferragens",            peso_percentual:0.24,  fase_numero:5,  momento_numero:2  },
  { ranking:48, classe:"C", nome:"Proteção de piso",                    categoria:"Acabamentos",          peso_percentual:0.23,  fase_numero:12, momento_numero:6  },
  { ranking:49, classe:"C", nome:"Padrão de energia",                   categoria:"Elétrica",             peso_percentual:0.23,  fase_numero:8,  momento_numero:1  },
  { ranking:50, classe:"C", nome:"Ferramentas",                         categoria:"Equipamentos",         peso_percentual:0.22,  fase_numero:22, momento_numero:1  },
  { ranking:51, classe:"C", nome:"Furos em concreto",                   categoria:"Estrutura",            peso_percentual:0.20,  fase_numero:5,  momento_numero:3  },
  { ranking:52, classe:"C", nome:"Piso intertravado (bloquete)",        categoria:"Pavimentação",         peso_percentual:0.16,  fase_numero:19, momento_numero:7  },
  { ranking:53, classe:"C", nome:"Portas de madeira",                   categoria:"Esquadrias",           peso_percentual:0.32,  fase_numero:14, momento_numero:8  },
  { ranking:54, classe:"C", nome:"Barracão de obra",                    categoria:"Canteiro",             peso_percentual:0.15,  fase_numero:2,  momento_numero:1  },
  { ranking:55, classe:"C", nome:"Instalações de Gás",                  categoria:"Instalações Especiais",peso_percentual:0.13,  fase_numero:10, momento_numero:3  },
  { ranking:56, classe:"C", nome:"Conta de água",                       categoria:"Taxas",                peso_percentual:0.13,  fase_numero:2,  momento_numero:null },
  { ranking:57, classe:"C", nome:"Drenagens",                           categoria:"Hidráulica",           peso_percentual:0.13,  fase_numero:9,  momento_numero:3  },
  { ranking:58, classe:"C", nome:"Blocos de concreto",                  categoria:"Alvenaria",            peso_percentual:0.13,  fase_numero:6,  momento_numero:2  },
  { ranking:59, classe:"C", nome:"Calhas e rufos",                      categoria:"Cobertura",            peso_percentual:0.13,  fase_numero:13, momento_numero:4  },
  { ranking:60, classe:"C", nome:"Betoneira",                           categoria:"Equipamentos",         peso_percentual:0.12,  fase_numero:22, momento_numero:2  },
  { ranking:61, classe:"C", nome:"Espaçadores plásticos",               categoria:"Estrutura",            peso_percentual:0.11,  fase_numero:5,  momento_numero:2  },
  { ranking:62, classe:"C", nome:"Martelete/Furadeira",                 categoria:"Equipamentos",         peso_percentual:0.10,  fase_numero:22, momento_numero:2  },
  { ranking:63, classe:"C", nome:"Locações diversas",                   categoria:"Locações",             peso_percentual:0.08,  fase_numero:22, momento_numero:null },
  { ranking:64, classe:"C", nome:"Conta de luz",                        categoria:"Taxas",                peso_percentual:0.08,  fase_numero:2,  momento_numero:null },
  { ranking:65, classe:"C", nome:"Limpeza de terreno",                  categoria:"Terreno",              peso_percentual:0.07,  fase_numero:1,  momento_numero:1  },
  { ranking:66, classe:"C", nome:"Compactador a gasolina",              categoria:"Equipamentos",         peso_percentual:0.07,  fase_numero:1,  momento_numero:1  },
  { ranking:67, classe:"C", nome:"Vibrador concretagem",                categoria:"Equipamentos",         peso_percentual:0.07,  fase_numero:22, momento_numero:2  },
  { ranking:68, classe:"C", nome:"Guincho de coluna",                   categoria:"Equipamentos",         peso_percentual:0.07,  fase_numero:22, momento_numero:2  },
  { ranking:69, classe:"C", nome:"Sondagem",                            categoria:"Fundação",             peso_percentual:0.06,  fase_numero:4,  momento_numero:1  },
  { ranking:70, classe:"C", nome:"Tapume",                              categoria:"Canteiro",             peso_percentual:0.06,  fase_numero:2,  momento_numero:1  },
  { ranking:71, classe:"C", nome:"Plotagens e papelaria",               categoria:"Administrativo",       peso_percentual:0.06,  fase_numero:3,  momento_numero:0  },
  { ranking:72, classe:"C", nome:"Emissão de Alvará",                   categoria:"Taxas",                peso_percentual:0.05,  fase_numero:3,  momento_numero:0  },
  { ranking:73, classe:"C", nome:"Infra de ar condicionado",            categoria:"Instalações Especiais",peso_percentual:0.09,  fase_numero:10, momento_numero:3  },
  { ranking:74, classe:"C", nome:"Locação de ferramentas",              categoria:"Locações",             peso_percentual:0.09,  fase_numero:22, momento_numero:null },
  { ranking:75, classe:"C", nome:"Serra de bancada",                    categoria:"Equipamentos",         peso_percentual:0.08,  fase_numero:22, momento_numero:null },
  { ranking:76, classe:"C", nome:"Rodapé",                              categoria:"Acabamentos",          peso_percentual:0.06,  fase_numero:12, momento_numero:6  },
  { ranking:77, classe:"C", nome:"Rejuntes",                            categoria:"Revestimentos",        peso_percentual:0.06,  fase_numero:12, momento_numero:6  },
  { ranking:78, classe:"C", nome:"Telhado fibrocimento",                categoria:"Cobertura",            peso_percentual:0.05,  fase_numero:13, momento_numero:4  },
  { ranking:79, classe:"C", nome:"Caminhão pipa",                       categoria:"Logística",            peso_percentual:0.05,  fase_numero:2,  momento_numero:null },
  { ranking:80, classe:"C", nome:"Produtos de limpeza",                 categoria:"Canteiro",             peso_percentual:0.04,  fase_numero:20, momento_numero:8  },
  { ranking:81, classe:"C", nome:"Desmoldantes",                        categoria:"Estrutura",            peso_percentual:0.04,  fase_numero:5,  momento_numero:2  },
  { ranking:82, classe:"C", nome:"Brita",                               categoria:"Estrutura",            peso_percentual:0.04,  fase_numero:4,  momento_numero:1  },
  { ranking:83, classe:"C", nome:"Pó de pedra",                         categoria:"Estrutura",            peso_percentual:0.03,  fase_numero:7,  momento_numero:3  },
  { ranking:84, classe:"C", nome:"Gasolina",                            categoria:"Canteiro",             peso_percentual:0.02,  fase_numero:2,  momento_numero:null },
  { ranking:85, classe:"C", nome:"ARTs de execução e projetos",         categoria:"Administrativo",       peso_percentual:0.02,  fase_numero:3,  momento_numero:0  },
  { ranking:86, classe:"C", nome:"Lavadora alta pressão",               categoria:"Equipamentos",         peso_percentual:0.01,  fase_numero:20, momento_numero:8  },
]
